### PR TITLE
fix: reset transform when switch

### PR DESCRIPTION
**Pull request by linxianxi**
fix https://github.com/ant-design/ant-design/issues/42693

### CODE REVIEW

**Comment by zombieJ** [comment]
加个 test case 哈~

**Comment by afc163** [comment]
+1

**Comment by linxianxi** [comment]
加了

**Comment by afc163** [comment]
用例挂了，更新一下 snapshot

**Comment by afc163** [comment]
发了 https://github.com/react-component/image/releases/tag/v5.17.1

还需要到 antd 里升级一下 rc-image 版本，验证是否有问题。

**Pull request merged**
