### PR TITLE
fix(Image): should show error img in previewGroup

### PR DESCRIPTION
**Pull request by huangkairan**
close https://github.com/ant-design/ant-design/issues/38112

### CODE REVIEW

**Comment by huangkairan** [comment]
@zombieJ 豆酱帮忙看下这个CI compile error
image

**Comment by afc163** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/62793

**Comment by huangkairan** [comment]
> [DefinitelyTyped/DefinitelyTyped#62793](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/62793)

@afc163 看了下是把@types/keyv/index.d.ts移除了，我能做什么吗

**Comment by zombieJ** [comment]
#131 已修复

**Pull request merged**
